#! /bin/sh
redshift -P -O 3000 -b 0.9 &
betterlockscreen -l dim -u ~/.config/bspwm/wallpaper.jpg
picom -f &
nitrogen --set-auto ~/.config/bspwm/wallpaper.jpg &
flameshot &
xsetroot -cursor_name left_ptr &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d Editor Terminal Browser Communication 'Extra 1' 'Extra 2'

bspc config border_width         1
bspc config border_radius        10
bspc config window_gap           10
bspc config top_padding          27

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config focused_border_color \#ffb52a

bspc rule -a Alacritty:Editor desktop=Editor
bspc rule -a Alacritty:Terminal1 desktop=Terminal
bspc rule -a Alacritty:Terminal2 desktop=Terminal
bspc rule -a Google-chrome desktop=Browser
bspc rule -a Slack desktop=Communication
bspc rule -a discord desktop=Communication

~/.config/polybar/launch.sh
~/.config/bspwm/start.sh
